image: node:24
stages:
  - install
  - build
  - test
  - docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
    - npx tsc --version

build:
  stage: build
  script:
    - npx tsc

test:
  stage: test
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - coverage/

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t user-manager-api .
